staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/tools


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 3933
# - Commit ID: cbf4f131e5c7c40c819ccd60612150bcecc5cb70
# - Timestamp: 2025-12-01T09:03:02Z
