staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/tools


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 3964
# - Commit ID: 425623f921bd20c623bf0358927cabceca5011ea
# - Timestamp: 2024-05-30T11:36:03Z
