staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/tools


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 2019
# - Commit ID: f4001312f91f6b380103fe75d03e21c451200e53
# - Timestamp: 2024-05-22T13:16:39Z
