////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

https://github.com/apache/logging-log4j-tools/actions[image:https://github.com/apache/logging-log4j-tools/workflows/build/badge.svg[Actions Status]]
https://search.maven.org/search?q=g:org.apache.logging.log4j.tools%20a:log4j-tools[image:https://img.shields.io/maven-central/v/org.apache.logging.log4j.tools/log4j-tools.svg[Maven Central]]
https://www.apache.org/licenses/LICENSE-2.0.txt[image:https://img.shields.io/github/license/apache/logging-log4j-tools.svg[License]]

Tooling **internally** used by https://logging.apache.org/log4j/2.x/[the Apache Log4j project] infrastructure.

xref:log4j-changelog/README.adoc[`log4j-changelog`]::
Tooling to export AsciiDoc-formatted changelog files.

= Support

Please keep in mind that this project is intended for internal usage only.
You can use GitHub Issues for feature requests and bug reports – not questions!
For the rest, you can use mailto:security@logging.apache.org[the Log4j development mailing list].

include::SECURITY.adoc[]

= License

Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.
See the NOTICE file distributed with this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0[].

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
